# Generated by Django 3.2.16 on 2022-11-09 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='games',
            options={'verbose_name_plural': 'Jogos'},
        ),
        migrations.CreateModel(
            name='Bets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1_score', models.PositiveSmallIntegerField()),
                ('team2_score', models.PositiveSmallIntegerField()),
                ('fk_gameId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.games')),
                ('fk_userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Apostas',
            },
        ),
    ]
